# this sets your path correctly so the imports work
import sys
import os
sys.path.insert(1, os.path.dirname(os.getcwd()))

from api import QuorumAPI
import json
# this library will let us turn dictionaries into csv files
import csv


class ChoroplethVisualizer(object):

    def get_members_by_state(self):
        """
        Creates a dictionary with state names as keys
        and representatives/senators from those states as values.
        """

    def save_members_by_state_json(self):
        """
        Creates a json file (serialized file) of the dictionary
        generated by above function so that it can be easily reaccessed
        without having to repeatedly call the above function.
        """

    def parse_members_by_state_json(self):
        """
        Parses and returns the dictionary contained in the file containing
        the members by state dictionary.
        """

    def save_state_csv(self, item_dict, file_name):
        """
        Takes in a dictionary (item_dict) and produces a two-column
        CSV (named file_name) of the format:
        state,num
        Alabama,9
        Montana,4
        ...etc
        """

    def get_word_mentions_per_state(self, word):
        """
        For the given word, get the number of documents per state that it is mentioned in.
        Write this to the data.csv file.
        """

cv = ChoroplethVisualizer()

# the word that we are building the choropleth about!
word = "representation"

cv.get_word_mentions_per_state(word)
